# Generated by Django 5.1 on 2024-08-31 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publikation',
            new_name='Publication',
        ),
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default='chat', max_length=50),
        ),
    ]
