# Generated by Django 5.1 on 2024-09-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_message_chat_message_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('bio', models.TextField(max_length=40000)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
