# Generated by Django 5.1 on 2024-09-01 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='bio',
            field=models.TextField(blank=True, max_length=40000, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
