# Generated by Django 5.1 on 2024-09-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_userdata_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='chat',
            new_name='user',
        ),
    ]
