# Generated by Django 5.1 on 2024-09-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_remove_chat_members_chat_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
