# Generated by Django 5.0.7 on 2024-12-13 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_remove_chat_members_chat_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='network.userdata'),
        ),
    ]
